== Zadanie 1 - Neo4j

* Zainstalować na swoim komputerze bazę http://neo4j.com[Neo4j].
* Przeczytać artykuł http://neo4j.com/blog/import-10m-stack-overflow-questions[Import 10M Stack Overflow Questions into Neo4j In Just 3 Minutes] i wykonać kod z tego artykułu.
* Opisać wszystkio to co się zdarzyło w jakimś repozytorium w pliku README.adoc (w formacie http://asciidoctor.org/[AsciiDoc]).

==== Download Stack Exchange Dump Files
Należy pobrać 3 pliki:
link:https://archive.org/download/stackexchange/stackoverflow.com-Posts.7z[Posts.7z],
link:https://archive.org/download/stackexchange/stackoverflow.com-Tags.7z[Tags.7z],
link:https://archive.org/download/stackexchange/stackoverflow.com-Users.7z[Users.7z]

==== Unzip the .7z Files
Plik pobierał się 7 godzin, po czy się zepsuł i nie można go rozpakować.

Po ponownej próbie udało się pobrać i rozpakować pliki.
Rozpakowujemy poleceniem:

`for i in *.7z; do 7za -y -oextracted x $i; done`

==== Clone Damien’s GitHub repository
Kolejnym krokiem będzie sklonowanie repozytorium. Można to zrobić następującym poleceniem:

`git clone https://github.com/mdamien/stackoverflow-neo4j`

Następnym krokiem jest isntalacja Pythona, gdyż będzie on potrzebny. Ja używam Systemu Fedora, dlatego używam następujących komend.

`sudo su`

`yum install python3-setuptools`

`sudo pip3 install xmltodict`

=== Run the XML-to-CSV Conversion

Konwertujemy pliki za pomocą komendy:

python3 to_csv.py extracted

czas trwania konwersji 3,5h
